import Head from "next/head";
import GradientBackground from "~/components/GradientBackground";
import { HeroSection } from "~/pages/HeroSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <GradientBackground
        xPosition={90}
        yPosition={5}
        from="#ef1a8e 0%"
        to="transparent 80%"
        opacity={0.2}
        radius={500}
      />
      <GradientBackground
        xPosition={10}
        yPosition={45}
        from="#691def 0%"
        to="transparent 80%"
        opacity={0.2}
        radius={750}
      />
    </>
  );
}
