import Image from "next/image";

import { PrimaryLinkButton } from "~/components/PrimaryLinkButton";

export function HeroBanner() {
  return (
    <section className="my-24 grid grid-cols-1 items-center gap-16 px-4 sm:grid-cols-2">
      <div className="order-2 flex flex-col gap-6 sm:order-1">
        <h1 className="text-6xl">Icon Generator</h1>
        <p className="text-3xl">Generate your icons with the help of AI</p>
        <PrimaryLinkButton href="/generate" className="self-start">
          Generate your icons
        </PrimaryLinkButton>
      </div>
      <Image
        src="/banner.png"
        alt="grid of icons generated by AI"
        width="400"
        height="300"
        className="order-1 sm:order-2"
      />
    </section>
  );
}
